Dyd.BaseService.Monitor.Web/Areas/Cluster/Controllers/PerformanceCollectController.cs
using Dyd.BaseService.Monitor.Domain.Chart.Model;
using Dyd.BaseService.Monitor.Domain.Cluster.Dal;
using Dyd.BaseService.Monitor.Domain.Cluster.Model;
using Dyd.BaseService.Monitor.Domain.PlatformManage.Dal;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;
using Webdiyer.WebControls.Mvc;
using XXF.Db;

namespace Web.Areas.Cluster.Controllers
{
    [AuthorityCheck]
    public class PerformanceCollectController : Controller
    {
        //
        // GET: /Cluster/PerformanceCollect/

        public ActionResult Index(string serverid,string serverip, string timebegin,string timeend,string orderby="", int pageindex = 1, int pagesize = 15)
        {
            ViewBag.serverid = serverid;
            ViewBag.serverip = serverip;
            if (string.IsNullOrWhiteSpace(timebegin))
            {
                timebegin = DateTime.Now.AddHours(-1).ToString("yyyy-MM-dd HH:mm");
            }
            ViewBag.timebegin = timebegin;
            if (string.IsNullOrWhiteSpace(timeend))
            {
                timeend = DateTime.Now.AddHours(1).ToString("yyyy-MM-dd HH:mm");
            }
            ViewBag.timeend = timeend;

            ViewBag.orderby = orderby;
            tb_performance_collect_dal dal = new tb_performance_collect_dal();
            PagedList<tb_performance_collect_model> pageList = null;
            int count = 0;
            using (DbConn PubConn = DbConfig.CreateConn(Config.ClusterConnectString))
            {
                PubConn.Open();
                List<tb_performance_collect_model> List = dal.GetList(PubConn, Dyd.BaseService.Monitor.Core.CoreGlobalConfig.GetConnStringDbName(Config.PlatformManageConnectString), serverid, serverip, timebegin, timeend, orderby, pagesize, pageindex, out count);
                pageList = new PagedList<tb_performance_collect_model>(List, pageindex, pagesize, count);
            }
            if (Request.IsAjaxRequest())
            {
                return PartialView("List", pageList);
            }
            return View(pageList);
        }

        public ActionResult Chart(string serverip, string serverid, string date, string columns = "cpu,memory,ioread,iowrite,networkupload,networkdownload", string datatype = "avg")
        {
            if (string.IsNullOrWhiteSpace(date))
                date = DateTime.Now.Date.ToString("yyyy-MM-dd");
            ViewBag.columns = columns; ViewBag.serverip = serverip; ViewBag.serverid = serverid; ViewBag.date = date; ViewBag.datatype = datatype;
            List<TimeChartModel> ms = new List<TimeChartModel>();
            if (string.IsNullOrWhiteSpace(serverip) && string.IsNullOrWhiteSpace(serverid))
            {
                return View(ms);
            }
            TimeChartDataType chartdatatype = (TimeChartDataType)Enum.Parse(typeof(TimeChartDataType), datatype);
            TimeChartType charttype = TimeChartType.Day;

            if (date.Split('-').Length == 3)
                charttype = TimeChartType.Day;
            else if (date.Split('-').Length == 2)
                charttype = TimeChartType.Month;
            else if (date.Split('-').Length == 1)
            {
                charttype = TimeChartType.Year;
                date = new DateTime(Convert.ToInt32(date), 1, 1, 0, 0, 0).ToString("yyyy-MM-dd");
            }

            var startDate = DateTime.Parse(date).Date;
            string[] cs = columns.TrimEnd(',').Split(',');

            foreach (var c in cs)
            {
                if (c == "")
                    continue;
                var model = new TimeChartModel();
                model.DataType = chartdatatype;
                model.Type = charttype;
                model.StartDate = startDate;
                model.Key = c;
                if (c == "cpu")
                {
                    model.Title = "CPU";
                    model.UnitText = "%";
                }
                if (c == "memory")
                {
                    model.Title = "可用内存";
                    model.UnitText = "M";
                }
                if (c == "networkupload")
                {
                    model.Title = "网络上传";
                    model.UnitText = "Byte";
                }
                if (c == "networkdownload")
                {
                    model.Title = "网络下载";
                    model.UnitText = "Byte";
                }
                if (c == "ioread")
                {
                    model.Title = "磁盘读";
                    model.UnitText = "Byte";
                }
                if (c == "iowrite")
                {
                    model.Title = "磁盘写";
                    model.UnitText = "Byte";
                }
                if (c == "iisrequest")
                {
                    model.Title = "iis请求";
                    model.UnitText = "次/s";
                }
                model.SubTitle = model.Title + "【" + model.DataType.ToString() + "】值统计图";
                if (model.Type == TimeChartType.Day)
                {
                    model.PointInterval = "60 * 1000";//一分钟
                    model.EndDate = model.StartDate.AddDays(1);
                    model.MaxZoom = "60 * 60 * 1000";
                    model.SubTitle += ",采集单位【分钟】";
                }
                else if (model.Type == TimeChartType.Month)
                {
                    model.PointInterval = "24 * 60 * 60 * 1000";//一天
                    model.EndDate = model.StartDate.AddMonths(1);
                    model.MaxZoom = "10 * 24 * 60 * 60 * 1000";
                    model.SubTitle += ",采集单位【天】";
                }
                else if (model.Type == TimeChartType.Year)
                {
                    model.PointInterval = "24 * 60 * 60 * 1000";//一天
                    model.EndDate = model.StartDate.AddYears(1);
                    model.MaxZoom = "10 * 24 * 60 * 60 * 1000";
                    model.SubTitle += ",采集单位【天】";
                }


                Dictionary<DateTime, double> dic = new Dictionary<DateTime, double>();
                using (DbConn PubConn = DbConfig.CreateConn(Config.ClusterConnectString))
                {
                    PubConn.Open();
                    if (model.Type == TimeChartType.Day)
                    {
                        tb_performance_collect_dal dal = new tb_performance_collect_dal();
                        dic = dal.GetTimeChart(PubConn, Dyd.BaseService.Monitor.Core.CoreGlobalConfig.GetConnStringDbName(Config.PlatformManageConnectString), c, model.StartDate, serverip, serverid, model.DataType.ToString());
                    }
                    else
                    {
                        tb_performance_dayreport_dal dal = new tb_performance_dayreport_dal();
                        dic = dal.GetTimeChart(PubConn,Dyd.BaseService.Monitor.Core.CoreGlobalConfig.GetConnStringDbName(Config.PlatformManageConnectString), c, model.StartDate, model.EndDate, serverip, serverid, model.DataType.ToString());
                    }
                }

                DateTime dtbegin = model.StartDate; DateTime dtend = model.EndDate;
                while (true)
                {
                    if (!dic.ContainsKey(dtbegin))
                    {
                        dic.Add(dtbegin, 0);
                    }
                    if (model.Type == TimeChartType.Day)
                        dtbegin = dtbegin.AddMinutes(1);
                    else
                        dtbegin = dtbegin.AddDays(1);
                    if (dtbegin >= dtend)
                        break;
                }
                model.DataJson = new XXF.Serialization.JsonHelper().Serializer(dic.OrderBy(c1 => c1.Key).Select(c1 => c1.Value));
                ms.Add(model);
            }
            using (DbConn PubConn = DbConfig.CreateConn(Config.PlatformManageConnectString))
            {
                PubConn.Open();
                tb_cluster_dal dal = new tb_cluster_dal();
                ViewBag.ServerName = dal.GetServerName(PubConn, serverip, serverid);
            }
            return View(ms);
        }

        public ActionResult ChartLoad(string key, int num = -3)
        {
            if (string.IsNullOrWhiteSpace(key))
            {
                return Json(new { code = -1, msg = "参数丢失" });
            }
            tb_performance_collect_dal dal = new tb_performance_collect_dal();
            using (DbConn PubConn = DbConfig.CreateConn(Config.ClusterConnectString))
            {
                PubConn.Open();
                Dictionary<string, List<ChartMainModel>> model = dal.GetMainChartJson(PubConn, num, key);
                return Json(new { code = 1, data = model });
            }
        }

        public ActionResult ChartJson(string Fday, string Nday, string key, string columnname)
        {
            if (string.IsNullOrWhiteSpace(key))
            {
                return Json(new { code = -1, msg = "参数丢失" });
            }
            if (string.IsNullOrWhiteSpace(columnname))
            {
                return Json(new { code = -1, msg = "请选择比较的参数" });
            }
            if (Fday == Nday)
            {
                return Json(new { code = -1, msg = "时间不能一样" });
            }
            try
            {
                List<string> day = new List<string>();
                day.Add(Fday);
                day.Add(Nday);
                tb_performance_collect_dal dal = new tb_performance_collect_dal();
                Dictionary<string, List<ChartSubModel>> model = new Dictionary<string, List<ChartSubModel>>();
                using (DbConn PubConn = DbConfig.CreateConn(Config.ClusterConnectString))
                {
                    PubConn.Open();
                    model = dal.GetSubChartJson(PubConn, day, key, columnname);
                }
                return Json(new { code = 1, data = model });
            }
            catch (Exception ex)

Dyd.BaseService.Monitor.Web/Areas/Cluster/Controllers/PerformanceDayReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dyd.BaseService.Monitor.Domain.Cluster.Dal;
using Dyd.BaseService.Monitor.Domain.Cluster.Model;
using Webdiyer.WebControls.Mvc;
using XXF.Db;
using Web.Models;
using Dyd.BaseService.Monitor.Domain.Chart.Model;

namespace Web.Areas.Cluster.Controllers
{
    [AuthorityCheck]
    public class PerformanceDayReportController : Controller
    {
        //
        // GET: /Cluster/PerformanceDayReport/

        public ActionResult Index(string serverip,string serverid,string timebegin, string timeend,string orderby="", string datatype="", int pageindex = 1, int pagesize = 15)
        {
            if (string.IsNullOrWhiteSpace(timebegin))
                timebegin = DateTime.Now.Date.AddDays(-10).ToString("yyyy-MM-dd");
            ViewBag.timebegin = timebegin;
            if (string.IsNullOrWhiteSpace(timeend))
                timeend = DateTime.Now.Date.ToString("yyyy-MM-dd");
            ViewBag.timeend = timeend;
            ViewBag.orderby = orderby; ViewBag.datatype = datatype; ViewBag.serverip = serverip; ViewBag.serverid = serverid;
            tb_performance_dayreport_dal dal = new tb_performance_dayreport_dal();
            PagedList<tb_performance_dayreport_model> pageList = null;
            int count = 0;
            using (DbConn PubConn = DbConfig.CreateConn(Config.ClusterConnectString))
            {
                PubConn.Open();
                List<tb_performance_dayreport_model> List = dal.GetList(PubConn, Dyd.BaseService.Monitor.Core.CoreGlobalConfig.GetConnStringDbName(Config.PlatformManageConnectString), serverip, serverid, timebegin, timeend, orderby, datatype, pagesize, pageindex, out count);
                pageList = new PagedList<tb_performance_dayreport_model>(List, pageindex, pagesize, count);
            }
            if (Request.IsAjaxRequest())
            {
                return PartialView("List", pageList);
            }
            return View(pageList);
        }

        public ActionResult Chart(string Fday, string Nday, string key, int pageindex = 1)
        {
            if (string.IsNullOrWhiteSpace(Fday))
            {
                Fday = DateTime.Now.AddDays(-1).ToString("yyyy-MM-dd");
            }
            if (string.IsNullOrWhiteSpace(Nday))
            {
                Nday = DateTime.Now.ToString("yyyy-MM-dd");
            }
            if (string.IsNullOrWhiteSpace(key))
            {
                key = "avgcpu";
            }
            ViewBag.Fday = Fday;
            ViewBag.Nday = Nday;
            ViewBag.Key = key;
            List<ChartModel> model = new List<ChartModel>();
            PagedList<ChartModel> pageList = null;
            int pagesize = 10;
            int count = 0;
            tb_performance_dayreport_dal dal = new tb_performance_dayreport_dal();
            using (DbConn PubConn = DbConfig.CreateConn(Config.ClusterConnectString))
            {
                PubConn.Open();
                model = dal.GetKeyChartJson(PubConn, Fday, Nday, key, pagesize, pageindex, out count);
                pageList = new PagedList<ChartModel>(model, pageindex, pagesize, count);
            }
            if (Request.IsAjaxRequest())
            {
                return PartialView("List", pageList);
            }
            return View(pageList);
        }

        public ActionResult ChartJson(string Sday, string Eday, string key)
        {
            List<Dictionary<string, object>> dic = new List<Dictionary<string, object>>();
            tb_performance_dayreport_dal dal = new tb_performance_dayreport_dal();
            using (DbConn PubConn = DbConfig.CreateConn(Config.ClusterConnectString))
            {
                PubConn.Open();
                dic = dal.GetChartJson(PubConn, Sday, Eday, key);
            }
            return Json(new { data = dic });
        }
    }
}

Dyd.BaseService.Monitor.Web/Areas/Cluster/Views/PerformanceDayReport/Chart.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<Dyd.BaseService.Monitor.Domain.Chart.Model.ChartModel>
@{
    ViewBag.Title = "URL耗时每日统计图表";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Dictionary<int, Dyd.BaseService.Monitor.Domain.PlatformManage.Model.timewatchConnModel> dic =
        ViewBag.TimeWatchConn as Dictionary<int, Dyd.BaseService.Monitor.Domain.PlatformManage.Model.timewatchConnModel>;
}
<div class="head">
    <div class="title">
        URL耗时每日统计图表
    </div>
</div>
<div class="orderlist m10 myorder">
    <div class="item_list pt10">
        @using (Html.BeginForm("chart", "PerformanceDayReport", FormMethod.Get, new RouteValueDictionary { { "id", "searchForm" } }))      
        {
            <div class="item_list">
                <ul>
                    <li>
                        <input type="hidden" id="key" name="key" value="@ViewBag.Key" />
                        <label>时间</label>
                        <input type="text" class="text" autocomplete="off"name="FDay" id="FDay" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd',minDate:'1900-01-01',readOnly:true})" value="@ViewBag.Fday" />和
                        <input type="text" class="text" autocomplete="off"name="Nday" id="Nday" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd',minDate:'1900-01-01',readOnly:true})" value="@ViewBag.Nday" />
                    </li>
                    <li class="search">
                        <input type="submit" class="btn1" value="搜索" accesskey="S" /></li>
                </ul>
            </div>
        }
    </div>
    <div class="tab_cont">
        <div class="ChartList">
            @Html.Partial("ChartList",Model)
        </div>
    </div>
</div>
<input type="hidden" id="DataJson" value="@Newtonsoft.Json.JsonConvert.SerializeObject(Model).Replace("\r\n","");" />
<div id="NameList" class="NameList c"></div>
<div id="ChartBtn" class="c"></div>
<div id="chart_wrapper" class="ml10 mt10">
    <div id="maychart" ></div>
</div>
<script src="~/Scripts/Highcharts-4.0.3/js/highcharts.js"></script>
<script src="~/Scripts/HighChartPack.js"></script>
<script>
    $(document).ready(function () {
        CreateChart();
    });

    function CreateChart() {
        var pack = new HighChartPack();
        var namelist = new Array();
        namelist.push({ "name": "平均CPU", "value": "avgcpu" });
        namelist.push({ "name": "最大CPU", "value": "maxcpu" });
        namelist.push({ "name": "最小CPU", "value": "mincpu" });
        namelist.push({ "name": "平均内存", "value": "avgmemory" });
        namelist.push({ "name": "最大内存", "value": "maxmemory" });
        namelist.push({ "name": "最小内存", "value": "minmemory" });
        namelist.push({ "name": "平均上传", "value": "avgnetworkupload" });
        namelist.push({ "name": "最大上传", "value": "maxnetworkupload" });
        namelist.push({ "name": "最小上传", "value": "minnetworkupload" });
        namelist.push({ "name": "平均下载", "value": "avgnetworkdownload" });
        namelist.push({ "name": "最大下载", "value": "maxnetworkdownload" });
        namelist.push({ "name": "最小下载", "value": "minnetworkdownload" });
        namelist.push({ "name": "平均磁盘读", "value": "avgioread" });
        namelist.push({ "name": "最大磁盘读", "value": "maxioread" });
        namelist.push({ "name": "最小磁盘读", "value": "minioread" });
        namelist.push({ "name": "平均磁盘写", "value": "avgiowrite" });
        namelist.push({ "name": "最大磁盘写", "value": "maxiowrite" });
        namelist.push({ "name": "最小磁盘写", "value": "miniowrite" });
        namelist.push({ "name": "平均IIS请求", "value": "avgiisrequest" });
        namelist.push({ "name": "最大IIS请求", "value": "maxiisrequest" });
        namelist.push({ "name": "最小IIS请求", "value": "miniisrequest" });
        var namelist = new Array();
        var catelist = new Array();
        catelist.push('@ViewBag.Fday');
        catelist.push('@ViewBag.Nday');
        var data = $("#DataJson").val();
        pack.Init(namelist, data, catelist, "性能监控统计图表");
    }
</script>

Dyd.BaseService.Monitor.Web/Areas/Cluster/Views/PerformanceDayReport/ChartList.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<Dyd.BaseService.Monitor.Domain.Chart.Model.ChartModel>

<table>
    <tr>
        <th width="3%"><input type="checkbox" id="CheckAll" onclick="CheckAll()" />全选</th>
        <th width="10%">ServerId</th>
        <th width="10%">@ViewBag.Fday</th>
        <th width="10%">@ViewBag.Nday</th>
        <th width="10%">变化值</th>
        <th width="10%">百分比</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td><input type="checkbox" name="GroupList" value="@item.Tkey" /></td>
            <td><a href="@Url.Action("Chart", "PerformanceCollect", new { key = item.Tkey.Replace("_", "/"), type = 2 })">@item.Tkey</a></td>
            <td>@item.Avalue</td>
            <td>@item.Bvalue</td>
            <td @Html.Raw(item.UpDown==1?"style='color:red'":"")>@item.AsubB</td>
            <td>@(item.Avalue==0?"无法计算":(item.AsubB/item.Avalue*100).ToString("0.00"))</td>
        </tr>
    }
</table>
<div class="total pt10">
    <div class="fl">共<em>@Model.TotalPageCount</em>页<em>@Model.TotalItemCount</em>条记录，当前为第<em>@Model.CurrentPageIndex</em>页</div>
    @Html.Pager(Model,new PagerOptions{PageIndexParameterName = "pageindex",ShowPageIndexBox = true,PageIndexBoxType = PageIndexBoxType.TextBox, CssClass="mvcPager"})
</div>

Dyd.BaseService.Monitor.Web/Areas/Cluster/Views/PerformanceDayReport/Index.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<Dyd.BaseService.Monitor.Domain.Cluster.Model.tb_performance_dayreport_model>
@{
    ViewBag.Title = "服务器月性能表";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>

</style>
<div class="head">
    <div class="title">
        服务器月性能表
    </div>
</div>
<div class="orderlist m10 myorder">
    @*@using (Ajax.BeginForm("index", new RouteValueDictionary { { "id", "" } }, new AjaxOptions { UpdateTargetId = "List", HttpMethod = "post", InsertionMode = InsertionMode.Replace }, new RouteValueDictionary { { "id", "searchForm" } }))*@
    @using (Html.BeginForm("index", "PerformanceDayReport", FormMethod.Get, new RouteValueDictionary { { "id", "searchForm" } }))      
    {
        <div class="item_list pt10">
            <div class="item_list">
                <ul>
                   <li>
                        <label>服务器ip</label>
                        <input type="text" style="" name="serverip" class="smalltext" value="@ViewBag.serverip" />
                    </li>
                    <li>
                        <label>服务器id</label>
                        <input type="text" name="serverid" class="smalltext"  value="@ViewBag.serverid" />
                    </li>
                   
                    <li>
                        <label>日期</label><input type="text" id="searchTime"  class="smalltext"  name="timebegin" value="@ViewBag.timebegin" /> - <input type="text" id="searchTime" class="smalltext"  name="timeend" value="@ViewBag.timeend" />（必须为日期）
                    </li>
                    <li>
                        <label>降序</label>
                        <select name="orderby">
                            <option value="">日期</option>
                            <option value="cpu" @(ViewBag.orderby+""=="cpu"?"selected='selected'":"")>cpu</option>
                            <option value="memory" @(ViewBag.orderby+""=="memory"?"selected='selected'":"")>可用内存</option>
                            <option value="networkupload" @(ViewBag.orderby+""=="networkupload"?"selected='selected'":"")>上传流量</option>
                            <option value="networkdownload" @(ViewBag.orderby+""=="networkdownload"?"selected='selected'":"")>下载流量</option>
                            <option value="ioread" @(ViewBag.orderby+""=="ioread"?"selected='selected'":"")>磁盘读</option>
                            <option value="iowrite" @(ViewBag.orderby+""=="iowrite"?"selected='selected'":"")>磁盘写</option>
                            <option value="iisrequest" @(ViewBag.orderby+""=="iisrequest"?"selected='selected'":"")>iis请求</option>
                        </select>
                        <select name="datatype">
                            <option value="avg" @(ViewBag.orderby+""=="avg"?"selected='selected'":"")>平均</option>
                            <option value="max" @(ViewBag.orderby+""=="max"?"selected='selected'":"")>最大</option>
                            <option value="min" @(ViewBag.orderby+""=="min"?"selected='selected'":"")>最小</option>
                        </select>
                    </li>
                    <li class="search">
                        <input type="submit" class="btn1" value="搜索" accesskey="S" /></li>
                    <@*li><a href="@Url.Action("Chart")">查看图表</a></li>*@
                </ul>
            </div>
        </div>
    }
    <div class="tab_cont">
        <div class="List">
            @Html.Partial("List",Model)
        </div>
    </div>
</div>

Dyd.BaseService.Monitor.Web/Areas/Cluster/Views/PerformanceDayReport/List.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<Dyd.BaseService.Monitor.Domain.Cluster.Model.tb_performance_dayreport_model>
<style>
     tr b {
        color:black;
    }
    tr .order{
        color:red;
    }
   
</style>

<table>
    <tr>
        <th>日期</th>
        <th width="12%">IP[id]</th>
        <th>CPU(%)[avg,max,min]</th>
        <th>可用内存(M)[avg,max,min]</th>
        <th>上传流量(Byte)[avg,max,min]</th>
        <th>下载流量(Byte)[avg,max,min]</th>
        <th>磁盘读(Byte)[avg,max,min]</th>
        <th>磁盘写(Byte)[avg,max,min]</th>
        <th>IIS请求(s)[avg,max,min]</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td title="最后统计id:@item.lastmaxid,最后更新时间:@item.lastupdatetime"><b @Html.Raw(ViewBag.orderby.ToLower()==""?"class='order'":"")>@item.date.Date.ToString("yyyy-MM-dd")</b></td>
            <td  style="text-align:left"><a href="@Url.Action("Chart", "PerformanceCollect", new { Area="Cluster",serverip=item.serverip,date=item.date.ToString("yyyy-MM-dd"),datatype="avg" })" title="点击查看性能图" target="_blank"><b style="color:blue">@item.servername</b><br />@item.serverip [@item.serverid]</a></td>
            <td style="text-align:left"><b @Html.Raw((ViewBag.datatype+ViewBag.orderby).ToLower()=="avgcpu"?"class='order'":"")>@item.avgcpu</b>,
                 <b @Html.Raw((ViewBag.datatype+ViewBag.orderby).ToLower()=="maxcpu"?"class='order'":"")>@item.maxcpu</b>,
               <b @Html.Raw((ViewBag.datatype+ViewBag.orderby).ToLower()=="mincpu"?"class='order'":"")> @item.mincpu</b></td>
            <td style="text-align:left"><b @Html.Raw((ViewBag.datatype+ViewBag.orderby).ToLower()=="avgmemory"?"class='order'":"")>@item.avgmemory</b>,
                <b @Html.Raw((ViewBag.datatype+ViewBag.orderby).ToLower()=="maxmemory"?"class='order'":"")>@item.maxmemory</b>,
                <b @Html.Raw((ViewBag.datatype+ViewBag.orderby).ToLower()=="minmemory"?"class='order'":"")>@item.minmemory</b></td>
            <td style="text-align:left"><b @Html.Raw((ViewBag.datatype+ViewBag.orderby).ToLower()=="avgnetworkupload"?"class='order'":"")>@item.avgnetworkupload</b>,
                <b @Html.Raw((ViewBag.datatype+ViewBag.orderby).ToLower()=="maxnetworkupload"?"class='order'":"")>@item.maxnetworkupload</b>,
    <b @Html.Raw((ViewBag.datatype+ViewBag.orderby).ToLower()=="minnetworkupload"?"class='order'":"")>@item.minnetworkupload</b></td>
            <td style="text-align:left"><b @Html.Raw((ViewBag.datatype+ViewBag.orderby).ToLower()=="avgnetworkdownload"?"class='order'":"")>@item.avgnetworkdownload</b>,
                <b @Html.Raw((ViewBag.datatype+ViewBag.orderby).ToLower()=="maxnetworkdownload"?"class='order'":"")>@item.maxnetworkdownload</b>,
                <b @Html.Raw((ViewBag.datatype+ViewBag.orderby).ToLower()=="minnetworkdownload"?"class='order'":"")>@item.minnetworkdownload</b></td>
            <td style="text-align:left"><b @Html.Raw((ViewBag.datatype+ViewBag.orderby).ToLower()=="avgioread"?"class='order'":"")>@item.avgioread</b>,
                <b @Html.Raw((ViewBag.datatype+ViewBag.orderby).ToLower()=="maxioread"?"class='order'":"")>@item.maxioread</b>,
    <b @Html.Raw((ViewBag.datatype+ViewBag.orderby).ToLower()=="minioread"?"class='order'":"")>@item.minioread</b></td>
            <td style="text-align:left"><b @Html.Raw((ViewBag.datatype+ViewBag.orderby).ToLower()=="avgiowrite"?"class='order'":"")>@item.avgiowrite</b>,
               <b @Html.Raw((ViewBag.datatype+ViewBag.orderby).ToLower()=="maxiowrite"?"class='order'":"")>@item.maxiowrite</b>,
               <b @Html.Raw((ViewBag.datatype+ViewBag.orderby).ToLower()=="miniowrite"?"class='order'":"")>@item.miniowrite</b></td>
            <td style="text-align:left"><b @Html.Raw((ViewBag.datatype+ViewBag.orderby).ToLower()=="avgiisrequest"?"class='order'":"")>@item.avgiisrequest</b>,
                <b @Html.Raw((ViewBag.datatype+ViewBag.orderby).ToLower()=="maxiisrequest"?"class='order'":"")>@item.maxiisrequest</b>,
                <b @Html.Raw((ViewBag.datatype+ViewBag.orderby).ToLower()=="miniisrequest"?"class='order'":"")>@item.miniisrequest</b></td>
        </tr>
    }
</table>
<div class="total pt10">
    <div class="fl">共<em>@Model.TotalPageCount</em>页<em>@Model.TotalItemCount</em>条记录，当前为第<em>@Model.CurrentPageIndex</em>页</div>
    @Html.Pager(Model,new PagerOptions{PageIndexParameterName = "pageindex",ShowPageIndexBox = true,PageIndexBoxType = PageIndexBoxType.TextBox, CssClass="mvcPager"})
    @*@Ajax.Pager(Model, new PagerOptions { PageIndexParameterName = "pageindex", ShowPageIndexBox = true, PageIndexBoxType = PageIndexBoxType.DropDownList, ShowGoButton = false }, new MvcAjaxOptions { UpdateTargetId = "List", HttpMethod = "Post", DataFormId = "searchForm" }, new { @class = "pager_page" })*@
</div>