Dyd.BaseService.Monitor.Web/Areas/TimeWatchCustomer/Controllers/TimeWatchLogApiDayReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dyd.BaseService.Monitor.Domain.TimeWatch.Model;
using Dyd.BaseService.Monitor.Domain.TimeWatch.Dal;
using Webdiyer.WebControls.Mvc;
using XXF.Db;
using Web.Models;
using Dyd.BaseService.Monitor.Domain.Chart.Model;

namespace Web.Areas.TimeWatchCustomer.Controllers
{
    [AuthorityCheck]
    public class TimeWatchLogApiDayReportController : TimeWatchConnVisit
    {
        //
        // GET: /TimeWatchCustomer/TimeWatchLogApiDayReport/

        public ActionResult Index( string url, string timebegin, string timeend, string orderby = "", int connid = 0, int pagesize = 15, int pageindex = 1)
        {
            return this.ConnVisit(connid, (conn) =>
            {
                if (string.IsNullOrWhiteSpace(timebegin))
                    timebegin = DateTime.Now.Date.AddDays(-10).ToString("yyyy-MM-dd");
                if (string.IsNullOrWhiteSpace(timeend))
                    timeend = DateTime.Now.Date.ToString("yyyy-MM-dd");
                ViewBag.url = url; ViewBag.timebegin = timebegin; ViewBag.timeend = timeend; ViewBag.orderby = orderby;
                tb_timewatchlog_api_dayreport_dal dal = new tb_timewatchlog_api_dayreport_dal();
                PagedList<tb_timewatchlog_api_dayreport_model> pageList = null;
                int count = 0;
                using (DbConn PubConn = DbConfig.CreateConn(conn))
                {
                    PubConn.Open();
                    List<tb_timewatchlog_api_dayreport_model> List = dal.GetList(PubConn, url,timebegin,timeend,orderby, pagesize, pageindex, out count);
                    pageList = new PagedList<tb_timewatchlog_api_dayreport_model>(List, pageindex, pagesize, count);
                }
                if (Request.IsAjaxRequest())
                {
                    return PartialView("List", pageList);
                }
                return View(pageList);
            });
        }

        public ActionResult Chart(string Fday, string Nday, string key, int pageindex = 1, int connid = 0)
        {
            return this.ConnVisit(connid, (conn) =>
            {
                if (string.IsNullOrWhiteSpace(Fday))
                {
                    Fday = DateTime.Now.AddDays(-1).ToString("yyyy-MM-dd");
                }
                if (string.IsNullOrWhiteSpace(Nday))
                {
                    Nday = DateTime.Now.ToString("yyyy-MM-dd");
                }
                if (string.IsNullOrWhiteSpace(key))
                {
                    key = "avgtime";
                }
                ViewBag.Fday = Fday;
                ViewBag.Nday = Nday;
                ViewBag.Key = key;
                List<ChartModel> model = new List<ChartModel>();
                PagedList<ChartModel> pageList = null;
                int pagesize = 10;
                int count = 0;
                tb_timewatchlog_api_dayreport_dal dal = new tb_timewatchlog_api_dayreport_dal();
                using (DbConn PubConn = DbConfig.CreateConn(conn))
                {
                    PubConn.Open();
                    model = dal.GetKeyChartJson(PubConn, Fday, Nday, key, pagesize, pageindex, out count);
                    pageList = new PagedList<ChartModel>(model, pageindex, pagesize, count);
                }
                if (Request.IsAjaxRequest())
                {
                    return PartialView("List", pageList);
                }
                return View(pageList);
            });
        }

        public ActionResult ChartJson(int connid, string Sday, string Eday, string key)
        {
            return this.ConnVisit(connid, (conn) =>
            {
                List<Dictionary<string, object>> dic = new List<Dictionary<string, object>>();
                tb_timewatchlog_api_dayreport_dal dal = new tb_timewatchlog_api_dayreport_dal();
                using (DbConn PubConn = DbConfig.CreateConn(conn))
                {
                    PubConn.Open();
                    dic = dal.GetChartJson(PubConn, Sday, Eday, key);
                }
                return Json(new { data = dic });
            });
        }
    }
}

Dyd.BaseService.Monitor.Web/Areas/TimeWatchCustomer/Controllers/TimeWatchLogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dyd.BaseService.Monitor.Domain.TimeWatch.Model;
using Dyd.BaseService.Monitor.Domain.TimeWatch.Dal;
using Webdiyer.WebControls.Mvc;
using XXF.Db;
using Web.Models;
using Dyd.BaseService.Monitor.Domain.Chart.Model;

namespace Web.Areas.TimeWatchCustomer.Controllers
{
    [AuthorityCheck]
    public class TimeWatchLogController : TimeWatchConnVisit
    {
        //
        // GET: /TimeWatchCustomer/TimeWatchLog/

        public ActionResult Index(string timebegin, string timeend, string projectname, string fromip, string sqlip, string url, string logtag,string orderby, int logtype = -1, double timewatchmin = -1, double timewatchmax = -1, int connid = 0, int pagesize = 10, int pageindex = 1)
        {
            return this.ConnVisit(connid, (conn) =>
            {
                if (string.IsNullOrWhiteSpace(timebegin))
                    timebegin = DateTime.Now.AddHours(-1).ToString("yyyy-MM-dd HH:mm:ss");
                if (string.IsNullOrWhiteSpace(timeend))
                    timeend = DateTime.Now.AddHours(1).ToString("yyyy-MM-dd HH:mm:ss");
                ViewBag.timebegin = timebegin; ViewBag.timeend = timeend; ViewBag.timewatchmin = (timewatchmin == -1 ? "" : timewatchmin + ""); ViewBag.timewatchmax = (timewatchmax == -1 ? "" : timewatchmax + ""); ViewBag.projectname = projectname; ViewBag.logtype = logtype;
                ViewBag.fromip = fromip; ViewBag.sqlip = sqlip; ViewBag.logtag = logtag; ViewBag.orderby = orderby; ViewBag.url = url;
                tb_timewatchlog_dal dal = new tb_timewatchlog_dal();
                PagedList<tb_timewatchlog_model> pageList = null;
                int count = 0;
                using (DbConn PubConn = DbConfig.CreateConn(conn))
                {
                    PubConn.Open();
                    List<tb_timewatchlog_model> List = dal.GetList(PubConn, timebegin, timeend, timewatchmin, timewatchmax, projectname, logtype, logtag, fromip, sqlip, orderby, url,pagesize, pageindex, out count);
                    pageList = new PagedList<tb_timewatchlog_model>(List, pageindex, pagesize, count);
                }
                if (Request.IsAjaxRequest())
                {
                    return PartialView("List", pageList);
                }
                return View(pageList);
            });
        }

        //public ActionResult Chart(string key, int type = 1, int connid = 0)
        //{
        //    return this.ConnVisit(connid, (conn) =>
        //    {
        //        ViewBag.Key = key;
        //        ViewBag.Type = type;
        //        return View();
        //    });
        //}

        public ActionResult ChartLoad(string key, int num = -3, int connid = 0, int type = 1)
        { 
            return this.ConnVisit(connid, (conn) =>
            {
                if (string.IsNullOrWhiteSpace(key))
                {
                    return Json(new { code = -1, msg = "参数丢失" });
                }
                tb_timewatchlog_dal dal = new tb_timewatchlog_dal();
                using (DbConn PubConn = DbConfig.CreateConn(conn))
                {
                    PubConn.Open();
                    Dictionary<string, List<ChartMainModel>> model = dal.GetMainChartJson(PubConn, num, key, type);
                    return Json(new { code = 1, data = model });
                }
            });
        }

        public ActionResult ChartJson(int connid, string Fday,string Nday, string key, string columnname)
        {
            return this.ConnVisit(connid, (conn) =>
            {
                if (string.IsNullOrWhiteSpace(key))
                {
                    return Json(new { code = -1, msg = "参数丢失" });
                }
                if (string.IsNullOrWhiteSpace(columnname))
                {
                    return Json(new { code = -1, msg = "请选择比较的参数" });
                }
                try
                {
                    List<string> day = new List<string>();
                    day.Add(Fday);
                    day.Add(Nday);
                    tb_timewatchlog_dal dal = new tb_timewatchlog_dal();
                    Dictionary<string, List<ChartSubModel>> model = new Dictionary<string, List<ChartSubModel>>();
                    using (DbConn PubConn = DbConfig.CreateConn(conn))
                    {
                        PubConn.Open();
                        model = dal.GetSubChartJson(PubConn, day, key, columnname);
                    }
                    return Json(new { code = 1, data = model });
                }
                catch (Exception ex)
                {
                    return Json(new { code = -1, msg = "日表不存在无法比较" });
                }
            });
        }

        public ActionResult Chart(string logtag, string date, XXF.BaseService.Monitor.SystemRuntime.EnumTimeWatchLogType type= XXF.BaseService.Monitor.SystemRuntime.EnumTimeWatchLogType.ApiUrl, string datatype = "avg", int connid = 0, string columns="time")
        {
            return this.ConnVisit(connid, (conn) =>
          {
              if (string.IsNullOrWhiteSpace(date))
                  date = DateTime.Now.Date.ToString("yyyy-MM-dd");
              ViewBag.type = type; ViewBag.date = date; ViewBag.datatype = datatype; ViewBag.logtag = logtag; ViewBag.connid = connid; 
              List<TimeChartModel> ms = new List<TimeChartModel>();
              if (string.IsNullOrWhiteSpace(logtag))
              {
                  return View(ms);
              } 
              int a=0;
              if(!int.TryParse(logtag,out a))
              {
                  type = XXF.BaseService.Monitor.SystemRuntime.EnumTimeWatchLogType.ApiUrl;
              }
              TimeChartDataType chartdatatype = (TimeChartDataType)Enum.Parse(typeof(TimeChartDataType), datatype);
              TimeChartType charttype = TimeChartType.Day;

              if (date.Split('-').Length == 3)
                  charttype = TimeChartType.Day;
              else if (date.Split('-').Length == 2)
                  charttype = TimeChartType.Month;
              else if (date.Split('-').Length == 1)
              {
                  charttype = TimeChartType.Year;
                  date = new DateTime(Convert.ToInt32(date), 1, 1, 0, 0, 0).ToString("yyyy-MM-dd");
              }

              var startDate = DateTime.Parse(date).Date;
              string[] cs = columns.TrimEnd(',').Split(',');

              foreach (var c in cs)
              {
                  if (c == "")
                      continue;
                  var model = new TimeChartModel();
                  model.DataType = chartdatatype;
                  model.Type = charttype;
                  model.StartDate = startDate;
                  model.Key = c;
                  model.Title = "耗时";
                  model.UnitText = "秒";
                  if (model.DataType == TimeChartDataType.count)
                      model.UnitText = "次";

                  model.SubTitle = model.Title + "【" + model.DataType.ToString() + "】值统计图";
                  if (model.Type == TimeChartType.Day)
                  {
                      model.PointInterval = "60 * 1000";//一分钟
                      model.EndDate = model.StartDate.AddDays(1);
                      model.MaxZoom = "60 * 60 * 1000";
                      model.SubTitle += ",采集单位【分钟】";
                  }
                  else if (model.Type == TimeChartType.Month)
                  {
                      model.PointInterval = "24 * 60 * 60 * 1000";//一天
                      model.EndDate = model.StartDate.AddMonths(1);
                      model.MaxZoom = "10 * 24 * 60 * 60 * 1000";
                      model.SubTitle += ",采集单位【天】";
                  }
                  else if (model.Type == TimeChartType.Year)
                  {
                      model.PointInterval = "24 * 60 * 60 * 1000";//一天
                      model.EndDate = model.StartDate.AddYears(1);
                      model.MaxZoom = "10 * 24 * 60 * 60 * 1000";
                      model.SubTitle += ",采集单位【天】";
                  }


                  Dictionary<DateTime, double> dic = new Dictionary<DateTime, double>();
                  using (DbConn PubConn = DbConfig.CreateConn(conn))
                    {
                        if (model.Type == TimeChartType.Day)
                        {
                            if (type == XXF.BaseService.Monitor.SystemRuntime.EnumTimeWatchLogType.ApiUrl)
                            {
                                tb_timewatchlog_api_dal dal = new tb_timewatchlog_api_dal();
                                dic = dal.GetTimeChart(PubConn, c, model.StartDate, logtag, model.DataType.ToString(), (int)type + "");
                            }
                            else if (type == XXF.BaseService.Monitor.SystemRuntime.EnumTimeWatchLogType.SqlCmd)
                            { 
                                tb_timewatchlog_dal dal = new tb_timewatchlog_dal();
                                dic = dal.GetTimeChart(PubConn, c, model.StartDate,logtag, model.DataType.ToString(),(int)type+"");
                            }
                        }
                        else
                        {
                            if (type == XXF.BaseService.Monitor.SystemRuntime.EnumTimeWatchLogType.ApiUrl)
                            {
                                tb_timewatchlog_api_dayreport_dal dal = new tb_timewatchlog_api_dayreport_dal();
                                dic = dal.GetTimeChart(PubConn, c, model.StartDate, model.EndDate, logtag, model.DataType.ToString());
                            }
                            else if(type == XXF.BaseService.Monitor.SystemRuntime.EnumTimeWatchLogType.SqlCmd)
                            {
                                tb_timewatchlog_sql_dayreport_dal dal = new tb_timewatchlog_sql_dayreport_dal();

Dyd.BaseService.Monitor.Web/Areas/TimeWatchCustomer/Views/TimeWatchLogApiDayReport/Chart.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<Dyd.BaseService.Monitor.Domain.Chart.Model.ChartModel>
@{
    ViewBag.Title = "URL耗时每日统计图表";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Dictionary<int, Dyd.BaseService.Monitor.Domain.PlatformManage.Model.timewatchConnModel> dic =
        ViewBag.TimeWatchConn as Dictionary<int, Dyd.BaseService.Monitor.Domain.PlatformManage.Model.timewatchConnModel>;
}
<div class="head">
    <div class="title">
        URL耗时每日统计图表
    </div>
</div>
<div class="orderlist m10 myorder">
    <div class="item_list pt10">
        @using (Html.BeginForm("chart", "TimeWatchLogApiDayReport", FormMethod.Get, new RouteValueDictionary { { "id", "searchForm" } }))      
        {
            <div class="item_list">
                <ul>
                    <li>
                        <input type="hidden" id="key" name="key" value="@ViewBag.Key" />
                        <label>时间</label>
                        <input type="text" class="text" autocomplete="off"name="FDay" id="FDay" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd',minDate:'1900-01-01',readOnly:true})" value="@ViewBag.Fday" />和
                        <input type="text" class="text" autocomplete="off"name="Nday" id="Nday" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd',minDate:'1900-01-01',readOnly:true})" value="@ViewBag.Nday" />
                    </li>
                    <li>
                        <label>数据库</label>
                        <select name="connid" id="connid">
                            @foreach (KeyValuePair<int, Dyd.BaseService.Monitor.Domain.PlatformManage.Model.timewatchConnModel> d in dic)
                            { 
                                <option value="@d.Key"@Html.Raw(d.Key == ViewBag.Connid ? "selected=selected" : "") >@d.Value.name</option>
                            }
                        </select>
                    </li>
                    <li class="search">
                        <input type="submit" class="btn1" value="搜索" accesskey="S" /></li>
                </ul>
            </div>
        }
    </div>
    <div class="tab_cont">
        <div class="ChartList">
            @Html.Partial("ChartList",Model)
        </div>
    </div>
</div>
<input type="hidden" id="DataJson" value="@Newtonsoft.Json.JsonConvert.SerializeObject(Model).Replace("\r\n","");" />
<div id="NameList" class="NameList c"></div>
<div id="ChartBtn" class="c"></div>
<div id="chart_wrapper" class="ml10 mt10">
    <div id="maychart" ></div>
</div>
<script src="~/Scripts/Highcharts-4.0.3/js/highcharts.js"></script>
<script src="~/Scripts/HighChartPack.js"></script>
<script>
    $(document).ready(function () {
        CreateChart();
    });

    function CreateChart() {
        var pack = new HighChartPack();
        var namelist = new Array();
        namelist.push({ "name": "平均耗时", "value": "avgtime" });
        namelist.push({ "name": "最大耗时", "value": "maxtime" });
        namelist.push({ "name": "最小耗时", "value": "mintime" });
        var catelist = new Array();
        catelist.push('@ViewBag.Fday');
        catelist.push('@ViewBag.Nday');
        var data = $("#DataJson").val();
        pack.Init(namelist, data, catelist, "URL性能统计图表");
    }
</script>

Dyd.BaseService.Monitor.Web/Areas/TimeWatchCustomer/Views/TimeWatchLogApiDayReport/ChartList.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<Dyd.BaseService.Monitor.Domain.Chart.Model.ChartModel>

<table>
    <tr>
        <th width="3%"><input type="checkbox" id="CheckAll" onclick="CheckAll()" />全选</th>
        <th width="10%">URL</th>
        <th width="10%">@ViewBag.Fday</th>
        <th width="10%">@ViewBag.Nday</th>
        <th width="10%">变化值</th>
        <th width="10%">百分比</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td><input type="checkbox" name="GroupList" value="@item.Tkey" /></td>
            <td><a href="@Url.Action("Chart", "TimeWatchLog", new { key = item.Tkey.Replace("_", "/"), type = 2 })">@item.Tkey</a></td>
            <td>@item.Avalue</td>
            <td>@item.Bvalue</td>
            <td @Html.Raw(item.UpDown==1?"style='color:red'":"")>@item.AsubB</td>
            <td>@(item.Avalue==0?"无法计算":(item.AsubB/item.Avalue*100).ToString("0.00"))</td>
        </tr>
    }
</table>
<div class="total pt10">
    <div class="fl">共<em>@Model.TotalPageCount</em>页<em>@Model.TotalItemCount</em>条记录，当前为第<em>@Model.CurrentPageIndex</em>页</div>
    @Html.Pager(Model,new PagerOptions{PageIndexParameterName = "pageindex",ShowPageIndexBox = true,PageIndexBoxType = PageIndexBoxType.TextBox, CssClass="mvcPager"})
</div>

Dyd.BaseService.Monitor.Web/Areas/TimeWatchCustomer/Views/TimeWatchLogApiDayReport/Index.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<Dyd.BaseService.Monitor.Domain.TimeWatch.Model.tb_timewatchlog_api_dayreport_model>
@{
    ViewBag.Title = "API月耗时表";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Dictionary<int, Dyd.BaseService.Monitor.Domain.PlatformManage.Model.timewatchConnModel> dic =
        ViewBag.TimeWatchConn as Dictionary<int, Dyd.BaseService.Monitor.Domain.PlatformManage.Model.timewatchConnModel>;
}
<div class="head">
    <div class="title">
        API月耗时表
    </div>
</div>
<div class="orderlist m10 myorder">
    @*@using (Ajax.BeginForm("index", new RouteValueDictionary { { "id", "" } }, new AjaxOptions { UpdateTargetId = "List", HttpMethod = "post", InsertionMode = InsertionMode.Replace }, new RouteValueDictionary { { "id", "searchForm" } }))*@
    @using (Html.BeginForm("index", "TimeWatchLogApiDayReport", FormMethod.Get, new RouteValueDictionary { { "id", "searchForm" } }))      
    {
        <div class="item_list pt10">
            <div class="item_list">
                <ul>
                   <li>
                        <label>Url</label>
                        <input type="text" name="url" value="@ViewBag.url" />
                    </li>
                    <li>
                        <label>降序</label>
                        <select name="orderby">
                            <option value="" @(ViewBag.orderby+""==""?"selected='selected'":"")>日期</option>
                            <option value="avgtime" @(ViewBag.orderby+""=="avgtime"?"selected='selected'":"")>平均时间</option>
                            <option value="maxtime" @(ViewBag.orderby+""=="maxtime"?"selected='selected'":"")>最大时间</option>
                            <option value="mintime" @(ViewBag.orderby+""=="mintime"?"selected='selected'":"")>最小时间</option>
                            <option value="count" @(ViewBag.orderby+""=="count"?"selected='selected'":"")>调用次数</option>
                        </select>
                    </li>
                    <li>
                        <label>数据库</label>
                        <select name="connid">
                            @foreach (KeyValuePair<int, Dyd.BaseService.Monitor.Domain.PlatformManage.Model.timewatchConnModel> d in dic)
                            { 
                                <option value="@d.Key"@Html.Raw(d.Key==ViewBag.Connid?"selected=selected":"") >@d.Value.name</option>
                            }
                        </select>
                       
                    </li>
                    <li>
                        <label>日期</label><input type="text"  class="smalltext"  name="timebegin" value="@ViewBag.timebegin" /> - <input type="text" class="smalltext"  name="timeend" value="@ViewBag.timeend" />（必须为日期）
                    </li>
                    
                </ul>
                 <input type="submit" class="btn1" value="搜索" accesskey="S" />
                      @*  <a href="@Url.Action("Chart")" class="btn1">查看图表</a>*@
            </div>
        </div>
    }
    <div class="tab_cont">
        <div class="List">
            @Html.Partial("List",Model)
        </div>
    </div>
</div>

Dyd.BaseService.Monitor.Web/Areas/TimeWatchCustomer/Views/TimeWatchLogApiDayReport/List.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<Dyd.BaseService.Monitor.Domain.TimeWatch.Model.tb_timewatchlog_api_dayreport_model>
@using XXF.Extensions;
<style>
         tr b {
        color:black;
    }
    tr .order{
        color:red;
    }
   
</style>
<table>
    <tr>
        <th>时间</th>
        <th>URL</th>
        <th>平均时间(s)</th>
        <th>最大时间(s)</th>
        <th>最小时间(s)</th>
        <th>调用次数</th><th>操作</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td  title="最后最大ID:@item.lastmaxid,最后更新时间:@item.lastupdatetime"><b @Html.Raw((ViewBag.orderby).ToLower()==""?"class='order'":"")>@item.date.Date.ToString("yyyy-MM-dd")</b></td>
            <td style="text-align:left"><a href="@Url.Action("Chart", "TimeWatchLog", new { Area="TimeWatchCustomer",logtag=item.url,type=(int)XXF.BaseService.Monitor.SystemRuntime.EnumTimeWatchLogType.ApiUrl,connid=ViewBag.Connid,date=item.date.ToString("yyyy-MM-dd"),datatype="avg" })" title="点击查看性能图" target="_blank">@item.url</a></td>
            <td><b @Html.Raw((ViewBag.orderby).ToLower()=="avgtime"?"class='order'":"")>@item.avgtime.ToString("f3")</b></td>
            <td><b @Html.Raw((ViewBag.orderby).ToLower()=="maxtime"?"class='order'":"")>@item.maxtime.ToString("f3")</b></td>
            <td><b @Html.Raw((ViewBag.orderby).ToLower()=="mintime"?"class='order'":"")>@item.mintime.ToString("f3")</b></td>
            <td><b @Html.Raw((ViewBag.orderby).ToLower()=="count"?"class='order'":"")>@item.count</b></td>
            <td class="caozuo"> 
                <a href="@Url.Action("Index", "TimeWatchLog", new { Area="TimeWatchCustomer",connid=ViewBag.Connid,logtag=item.url.GetHashCode(),timebegin=DateTime.Now.AddMinutes(-30).ToString("yyyy-MM-dd HH:mm:ss"),timeend=DateTime.Now.AddHours(1).ToString("yyyy-MM-dd HH:mm:ss") })"  target="_blank">当前耗时</a>
                <a href="@Url.Action("Index", "TimeWatchLogApiDayReport", new { Area="TimeWatchCustomer",url=item.url,connid=ViewBag.Connid,datatype="avg",timebegin=DateTime.Now.ToString("yyyy-MM-01"),timeend=DateTime.Now.ToString("yyyy-MM-dd") })"  target="_blank">当月耗时</a>
                <a href="@Url.Action("Chart", "TimeWatchLog", new { Area="TimeWatchCustomer",logtag=item.url,type=(int)XXF.BaseService.Monitor.SystemRuntime.EnumTimeWatchLogType.ApiUrl,connid=ViewBag.Connid,date=item.date.ToString("yyyy-MM-dd"),datatype="avg" })" target="_blank">api性能图</a>
                <a href="@Url.Action("Index", "SqlHashContrastUrl", new { Area="TimeWatchCustomer",connid=ViewBag.Connid,url=item.url })"  target="_blank">api相关sql</a>
            </td>
        </tr>
    }
</table>
<div class="total pt10">
    <div class="fl">共<em>@Model.TotalPageCount</em>页<em>@Model.TotalItemCount</em>条记录，当前为第<em>@Model.CurrentPageIndex</em>页</div>
    @Html.Pager(Model,new PagerOptions{PageIndexParameterName = "pageindex",ShowPageIndexBox = true,PageIndexBoxType = PageIndexBoxType.TextBox, CssClass="mvcPager"})
    @*@Ajax.Pager(Model, new PagerOptions { PageIndexParameterName = "pageindex", ShowPageIndexBox = true, PageIndexBoxType = PageIndexBoxType.DropDownList, ShowGoButton = false }, new MvcAjaxOptions { UpdateTargetId = "List", HttpMethod = "Post", DataFormId = "searchForm" }, new { @class = "pager_page" })*@
</div>