Dyd.BaseService.Monitor.Web/Areas/TimeWatchCustomer/Controllers/SqlHashConsultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dyd.BaseService.Monitor.Domain.TimeWatch.Model;
using Dyd.BaseService.Monitor.Domain.TimeWatch.Dal;
using Webdiyer.WebControls.Mvc;
using XXF.Db;
using Web.Models;

namespace Web.Areas.TimeWatchCustomer.Controllers
{
    [AuthorityCheck]
    public class SqlHashConsultController : TimeWatchConnVisit
    {
        //
        // GET: /TimeWatchCustomer/SqlHashConsult/

        public ActionResult Index(string sqlhash, string sql, string orderby = "count desc", int connid = 0, int extime = 0, int pagesize = 15, int pageindex = 1)
        {
            return this.ConnVisit(connid, (conn) =>
            {
                ViewBag.sqlhash = sqlhash; ViewBag.sql = sql; ViewBag.orderby = orderby;
                ViewBag.extime = extime;
                tb_sqlhash_consult_dal dal = new tb_sqlhash_consult_dal();
                PagedList<tb_sqlhash_consult_model> pageList = null;
                int count = 0;
                using (DbConn PubConn = DbConfig.CreateConn(conn))
                {
                    PubConn.Open();
                    List<tb_sqlhash_consult_model> List = dal.GetList(PubConn, sqlhash,sql,orderby, extime, pagesize, pageindex, out count);
                    pageList = new PagedList<tb_sqlhash_consult_model>(List, pageindex, pagesize, count);
                }
                if (Request.IsAjaxRequest())
                {
                    return PartialView("List", pageList);
                }
                return View(pageList);
            });
        }

        public ActionResult Chart(int connid = 0)
        {
            return this.ConnVisit(connid, (conn) =>
            {
                return View();
            });
        }

        public ActionResult ChartJson(int connid, int count = 0)
        {
            return this.ConnVisit(connid, (conn) =>
            {
                tb_sqlhash_consult_dal dal = new tb_sqlhash_consult_dal();
                List<tb_sqlhash_consult_model> model = new List<tb_sqlhash_consult_model>();
                using (DbConn PubConn = DbConfig.CreateConn(conn))
                {
                    PubConn.Open();
                    model = dal.GetChartJson(PubConn, count);
                }
                return Json(new { data = model });
            });
        }
    }
}

Dyd.BaseService.Monitor.Web/Areas/TimeWatchCustomer/Controllers/TimeWatchLogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dyd.BaseService.Monitor.Domain.TimeWatch.Model;
using Dyd.BaseService.Monitor.Domain.TimeWatch.Dal;
using Webdiyer.WebControls.Mvc;
using XXF.Db;
using Web.Models;
using Dyd.BaseService.Monitor.Domain.Chart.Model;

namespace Web.Areas.TimeWatchCustomer.Controllers
{
    [AuthorityCheck]
    public class TimeWatchLogController : TimeWatchConnVisit
    {
        //
        // GET: /TimeWatchCustomer/TimeWatchLog/

        public ActionResult Index(string timebegin, string timeend, string projectname, string fromip, string sqlip, string url, string logtag,string orderby, int logtype = -1, double timewatchmin = -1, double timewatchmax = -1, int connid = 0, int pagesize = 10, int pageindex = 1)
        {
            return this.ConnVisit(connid, (conn) =>
            {
                if (string.IsNullOrWhiteSpace(timebegin))
                    timebegin = DateTime.Now.AddHours(-1).ToString("yyyy-MM-dd HH:mm:ss");
                if (string.IsNullOrWhiteSpace(timeend))
                    timeend = DateTime.Now.AddHours(1).ToString("yyyy-MM-dd HH:mm:ss");
                ViewBag.timebegin = timebegin; ViewBag.timeend = timeend; ViewBag.timewatchmin = (timewatchmin == -1 ? "" : timewatchmin + ""); ViewBag.timewatchmax = (timewatchmax == -1 ? "" : timewatchmax + ""); ViewBag.projectname = projectname; ViewBag.logtype = logtype;
                ViewBag.fromip = fromip; ViewBag.sqlip = sqlip; ViewBag.logtag = logtag; ViewBag.orderby = orderby; ViewBag.url = url;
                tb_timewatchlog_dal dal = new tb_timewatchlog_dal();
                PagedList<tb_timewatchlog_model> pageList = null;
                int count = 0;
                using (DbConn PubConn = DbConfig.CreateConn(conn))
                {
                    PubConn.Open();
                    List<tb_timewatchlog_model> List = dal.GetList(PubConn, timebegin, timeend, timewatchmin, timewatchmax, projectname, logtype, logtag, fromip, sqlip, orderby, url,pagesize, pageindex, out count);
                    pageList = new PagedList<tb_timewatchlog_model>(List, pageindex, pagesize, count);
                }
                if (Request.IsAjaxRequest())
                {
                    return PartialView("List", pageList);
                }
                return View(pageList);
            });
        }

        //public ActionResult Chart(string key, int type = 1, int connid = 0)
        //{
        //    return this.ConnVisit(connid, (conn) =>
        //    {
        //        ViewBag.Key = key;
        //        ViewBag.Type = type;
        //        return View();
        //    });
        //}

        public ActionResult ChartLoad(string key, int num = -3, int connid = 0, int type = 1)
        { 
            return this.ConnVisit(connid, (conn) =>
            {
                if (string.IsNullOrWhiteSpace(key))
                {
                    return Json(new { code = -1, msg = "参数丢失" });
                }
                tb_timewatchlog_dal dal = new tb_timewatchlog_dal();
                using (DbConn PubConn = DbConfig.CreateConn(conn))
                {
                    PubConn.Open();
                    Dictionary<string, List<ChartMainModel>> model = dal.GetMainChartJson(PubConn, num, key, type);
                    return Json(new { code = 1, data = model });
                }
            });
        }

        public ActionResult ChartJson(int connid, string Fday,string Nday, string key, string columnname)
        {
            return this.ConnVisit(connid, (conn) =>
            {
                if (string.IsNullOrWhiteSpace(key))
                {
                    return Json(new { code = -1, msg = "参数丢失" });
                }
                if (string.IsNullOrWhiteSpace(columnname))
                {
                    return Json(new { code = -1, msg = "请选择比较的参数" });
                }
                try
                {
                    List<string> day = new List<string>();
                    day.Add(Fday);
                    day.Add(Nday);
                    tb_timewatchlog_dal dal = new tb_timewatchlog_dal();
                    Dictionary<string, List<ChartSubModel>> model = new Dictionary<string, List<ChartSubModel>>();
                    using (DbConn PubConn = DbConfig.CreateConn(conn))
                    {
                        PubConn.Open();
                        model = dal.GetSubChartJson(PubConn, day, key, columnname);
                    }
                    return Json(new { code = 1, data = model });
                }
                catch (Exception ex)
                {
                    return Json(new { code = -1, msg = "日表不存在无法比较" });
                }
            });
        }

        public ActionResult Chart(string logtag, string date, XXF.BaseService.Monitor.SystemRuntime.EnumTimeWatchLogType type= XXF.BaseService.Monitor.SystemRuntime.EnumTimeWatchLogType.ApiUrl, string datatype = "avg", int connid = 0, string columns="time")
        {
            return this.ConnVisit(connid, (conn) =>
          {
              if (string.IsNullOrWhiteSpace(date))
                  date = DateTime.Now.Date.ToString("yyyy-MM-dd");
              ViewBag.type = type; ViewBag.date = date; ViewBag.datatype = datatype; ViewBag.logtag = logtag; ViewBag.connid = connid; 
              List<TimeChartModel> ms = new List<TimeChartModel>();
              if (string.IsNullOrWhiteSpace(logtag))
              {
                  return View(ms);
              } 
              int a=0;
              if(!int.TryParse(logtag,out a))
              {
                  type = XXF.BaseService.Monitor.SystemRuntime.EnumTimeWatchLogType.ApiUrl;
              }
              TimeChartDataType chartdatatype = (TimeChartDataType)Enum.Parse(typeof(TimeChartDataType), datatype);
              TimeChartType charttype = TimeChartType.Day;

              if (date.Split('-').Length == 3)
                  charttype = TimeChartType.Day;
              else if (date.Split('-').Length == 2)
                  charttype = TimeChartType.Month;
              else if (date.Split('-').Length == 1)
              {
                  charttype = TimeChartType.Year;
                  date = new DateTime(Convert.ToInt32(date), 1, 1, 0, 0, 0).ToString("yyyy-MM-dd");
              }

              var startDate = DateTime.Parse(date).Date;
              string[] cs = columns.TrimEnd(',').Split(',');

              foreach (var c in cs)
              {
                  if (c == "")
                      continue;
                  var model = new TimeChartModel();
                  model.DataType = chartdatatype;
                  model.Type = charttype;
                  model.StartDate = startDate;
                  model.Key = c;
                  model.Title = "耗时";
                  model.UnitText = "秒";
                  if (model.DataType == TimeChartDataType.count)
                      model.UnitText = "次";

                  model.SubTitle = model.Title + "【" + model.DataType.ToString() + "】值统计图";
                  if (model.Type == TimeChartType.Day)
                  {
                      model.PointInterval = "60 * 1000";//一分钟
                      model.EndDate = model.StartDate.AddDays(1);
                      model.MaxZoom = "60 * 60 * 1000";
                      model.SubTitle += ",采集单位【分钟】";
                  }
                  else if (model.Type == TimeChartType.Month)
                  {
                      model.PointInterval = "24 * 60 * 60 * 1000";//一天
                      model.EndDate = model.StartDate.AddMonths(1);
                      model.MaxZoom = "10 * 24 * 60 * 60 * 1000";
                      model.SubTitle += ",采集单位【天】";
                  }
                  else if (model.Type == TimeChartType.Year)
                  {
                      model.PointInterval = "24 * 60 * 60 * 1000";//一天
                      model.EndDate = model.StartDate.AddYears(1);
                      model.MaxZoom = "10 * 24 * 60 * 60 * 1000";
                      model.SubTitle += ",采集单位【天】";
                  }


                  Dictionary<DateTime, double> dic = new Dictionary<DateTime, double>();
                  using (DbConn PubConn = DbConfig.CreateConn(conn))
                    {
                        if (model.Type == TimeChartType.Day)
                        {
                            if (type == XXF.BaseService.Monitor.SystemRuntime.EnumTimeWatchLogType.ApiUrl)
                            {
                                tb_timewatchlog_api_dal dal = new tb_timewatchlog_api_dal();
                                dic = dal.GetTimeChart(PubConn, c, model.StartDate, logtag, model.DataType.ToString(), (int)type + "");
                            }
                            else if (type == XXF.BaseService.Monitor.SystemRuntime.EnumTimeWatchLogType.SqlCmd)
                            { 
                                tb_timewatchlog_dal dal = new tb_timewatchlog_dal();
                                dic = dal.GetTimeChart(PubConn, c, model.StartDate,logtag, model.DataType.ToString(),(int)type+"");
                            }
                        }
                        else
                        {
                            if (type == XXF.BaseService.Monitor.SystemRuntime.EnumTimeWatchLogType.ApiUrl)
                            {
                                tb_timewatchlog_api_dayreport_dal dal = new tb_timewatchlog_api_dayreport_dal();
                                dic = dal.GetTimeChart(PubConn, c, model.StartDate, model.EndDate, logtag, model.DataType.ToString());
                            }
                            else if(type == XXF.BaseService.Monitor.SystemRuntime.EnumTimeWatchLogType.SqlCmd)
                            {
                                tb_timewatchlog_sql_dayreport_dal dal = new tb_timewatchlog_sql_dayreport_dal();

Dyd.BaseService.Monitor.Web/Areas/TimeWatchCustomer/Views/SqlHashConsult/Chart.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<Dyd.BaseService.Monitor.Domain.TimeWatch.Model.tb_timewatchlog_api_dayreport_model>
@{
    ViewBag.Title = "SQL图表";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Dictionary<int, Dyd.BaseService.Monitor.Domain.PlatformManage.Model.timewatchConnModel> dic =
        ViewBag.TimeWatchConn as Dictionary<int, Dyd.BaseService.Monitor.Domain.PlatformManage.Model.timewatchConnModel>;
}
<div class="head">
    <div class="title">
        SQL图表
    </div>
</div>
<div class="orderlist m10 myorder">
    <div class="item_list pt10">
        <div class="item_list">
            <ul>
                <li>
                    <label>次数大于</label>
                    <input type="text" class="text" id="count" name="count" value="0" />
                </li>
                <li>
                    <label>数据库</label>
                    <select name="connid" id="connid">
                        @foreach (KeyValuePair<int, Dyd.BaseService.Monitor.Domain.PlatformManage.Model.timewatchConnModel> d in dic)
                        { 
                            <option value="@d.Key"@Html.Raw(d.Key == ViewBag.Connid ? "selected=selected" : "") >@d.Value.name</option>
                        }
                    </select>
                </li>
                <li class="search">
                    <input type="button" class="btn1" value="搜索" onclick="CreateChart()" accesskey="S" /></li>
            </ul>
        </div>
    </div>
</div>
<div id="ChartBtn" class="c"></div>
<div>
    <div id="maychart"></div>
</div>
<div id="ChartAmp"></div>
<script src="~/Scripts/Highcharts-4.0.3/js/highcharts.js"></script>
<script src="~/Scripts/StreamCreateChart.js"></script>
<script>
    function CreateChart()
    {
        $.ajax({
            url: "/SqlHashConsult/ChartJson",
            data: {
                count: $("#count").val(),
                connid: $("#connid").find("option:selected").val()
            },
            type: "post",
            success: function (data) {
                var chart = new CreateChartStream();
                var namelist=new Array();
                namelist.push("count");
                chart.Init(data.data, "nodenotes", namelist, "空");
            }
        })
    }
</script>

Dyd.BaseService.Monitor.Web/Areas/TimeWatchCustomer/Views/SqlHashConsult/Index.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<Dyd.BaseService.Monitor.Domain.TimeWatch.Model.tb_sqlhash_consult_model>
@{
    ViewBag.Title = "Sql参照表";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Dictionary<int, Dyd.BaseService.Monitor.Domain.PlatformManage.Model.timewatchConnModel> dic =
        ViewBag.TimeWatchConn as Dictionary<int, Dyd.BaseService.Monitor.Domain.PlatformManage.Model.timewatchConnModel>;
}
<div class="head">
    <div class="title">
        Sql参照表
    </div>
</div>
<div class="orderlist m10 myorder">
    @*@using (Ajax.BeginForm("index", new RouteValueDictionary { { "id", "" } }, new AjaxOptions { UpdateTargetId = "List", HttpMethod = "post", InsertionMode = InsertionMode.Replace }, new RouteValueDictionary { { "id", "searchForm" } }))*@
    @using (Html.BeginForm("index", "SqlHashConsult", FormMethod.Get, new RouteValueDictionary { { "id", "searchForm" } }))      
    {
        <div class="item_list pt10">
            <div class="item_list">
                <ul>
                   <li>
                        <label>sql哈希码</label>
                        <input type="text" name="sqlhash"  class="smalltext"  value="@ViewBag.sqlhash" />
                    </li>
                    <li>
                        <label>sql语句</label>
                        <input type="text" name="sql" value="@ViewBag.sql" />
                    </li>
                     <li>
                        <label>排序</label>
                        <select name="orderby">
                            <option value="count desc" @Html.Raw(ViewBag.orderby+""=="count desc"?"selected='selected'":"")>数量降序</option>
                            <option value="count asc" @Html.Raw(ViewBag.orderby+""=="count asc"?"selected='selected'":"")>数量升序</option>
                        </select>
                    </li>
                    <li>
                        <label>数据库</label>
                        <select name="connid">
                            @foreach (KeyValuePair<int, Dyd.BaseService.Monitor.Domain.PlatformManage.Model.timewatchConnModel> d in dic)
                            { 
                                <option value="@d.Key"@Html.Raw(d.Key==ViewBag.Connid?"selected=selected":"") >@d.Value.name</option>
                            }
                        </select>
                        <input type="submit" class="btn1" value="搜索" accesskey="S" />
                        @*<a href="@Url.Action("Chart")" class="btn1">查看图表</a>*@
                    </li>
                </ul>
            </div>
        </div>
    }
    <div class="tab_cont">
        <div class="List">
            @Html.Partial("List",Model)
        </div>
    </div>
</div>

Dyd.BaseService.Monitor.Web/Areas/TimeWatchCustomer/Views/SqlHashConsult/List.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<Dyd.BaseService.Monitor.Domain.TimeWatch.Model.tb_sqlhash_consult_model>
@using XXF.Extensions;

<table>
    <tr>
        <th>Sql哈希码</th>
        
        <th>数量</th>
        <th>Sql语句</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td><a href="@Url.Action("Chart", "TimeWatchLog", new { key = item.sqlhash, type = 1 })">@item.sqlhash</a></td>
            <td>@item.count</td>
            <td  style="text-align:left; word-break:break-all;" title="@item.sql">@item.sql.SubString3(200)</td>
           
        </tr>
    }
</table>
<div class="total pt10">
    <div class="fl">共<em>@Model.TotalPageCount</em>页<em>@Model.TotalItemCount</em>条记录，当前为第<em>@Model.CurrentPageIndex</em>页</div>
    @Html.Pager(Model,new PagerOptions{PageIndexParameterName = "pageindex",ShowPageIndexBox = true,PageIndexBoxType = PageIndexBoxType.TextBox, CssClass="mvcPager"})
    @*@Ajax.Pager(Model, new PagerOptions { PageIndexParameterName = "pageindex", ShowPageIndexBox = true, PageIndexBoxType = PageIndexBoxType.DropDownList, ShowGoButton = false }, new MvcAjaxOptions { UpdateTargetId = "List", HttpMethod = "Post", DataFormId = "searchForm" }, new { @class = "pager_page" })*@
</div>